version: '3.8'

services:
    frontend:
      image: ex1-14-fr
      build: .
      container_name: simple-fr
    
    backend:
      image: ex1-14-ba
      build: .
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_PASSWORD=1234
      container_name: simple-ba

    redis:
      image: redis
      build: .
      container_name: redis

    postgres:
      image: postgres
      restart: unless-stopped
      volumes:
        - ./database:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: 1234
      container_name: postgres

    nginx:
      image: nginx
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      container_name: nginx